#!/bin/sh
export JSON_STRING='window.configs = { \
  "ROOT_API":"'${ROOT_API}'", \
  "KEYCLOAK_ISSUER":"'${KEYCLOAK_ISSUER}'", \
  "KEYCLOAK_CLIENT_ID":"'${KEYCLOAK_CLIENT_ID}'", \
  "KEYCLOAK_REALM":"'${KEYCLOAK_REALM}'", \
  "SENTRY_DSN_ENDPOINT":"'${SENTRY_DSN_ENDPOINT}'", \
  "HELPHERO":"'${HELPHERO}'", \
  "STRIPE_API":"'${STRIPE_API}'", \
  "BOT_URL":"'${BOT_URL}'", \
  "TWO_FA_APP_ANDROID":"'${TWO_FA_APP_ANDROID}'", \
  "TWO_FA_APP_IOS":"'${TWO_FA_APP_IOS}'", \
  "FLOWS_GENERIC_TOKEN":"'${FLOWS_GENERIC_TOKEN}'", \
  "MODULES_YAML":"'${MODULES_YAML}'", \
  "BRAIN_IS_SHOWN_FOR_PROJECTS":"'${BRAIN_IS_SHOWN_FOR_PROJECTS}'", \
  "BRAIN_IS_SHOWN_FOR_USERS":"'${BRAIN_IS_SHOWN_FOR_USERS}'", \
  "BRAIN_IS_SHOWN_FOR_USER_MANAGED_PROJECTS_FROM":"'${BRAIN_IS_SHOWN_FOR_USER_MANAGED_PROJECTS_FROM}'", \
  "NEXUS_API":"'${NEXUS_API}'", \
  "HOTJAR_ID":"'${HOTJAR_ID}'", \
  "BILLING_API_URL":"'${BILLING_API_URL}'", \
  "CHATS_API_URL":"'${CHATS_API_URL}'", \
  "PROJECTS_BOTHUB_ALLOWED":"'${PROJECTS_BOTHUB_ALLOWED}'", \
  "GITHUB_API":"'${GITHUB_API}'", \
  "GITHUB_CONTENT_API":"'${GITHUB_CONTENT_API}'", \
  "GITHUB_PLATFORM_UPDATES_REPOSITORY":"'${GITHUB_PLATFORM_UPDATES_REPOSITORY}'", \
  "TEMP_COMMERCE_ALLOWED_EMAILS":"'${TEMP_COMMERCE_ALLOWED_EMAILS}'", \
  "GROWTHBOOK_API_HOST":"'${GROWTHBOOK_API_HOST}'", \
  "GROWTHBOOK_CLIENT_KEY":"'${GROWTHBOOK_CLIENT_KEY}'", \
}'
sed "s|\/\/CONFIGURATIONS_PLACEHOLDER|${JSON_STRING}|" /usr/share/nginx/html/connect/index.html.tmpl > /tmp/index.html

exec "$@"
