#!/bin/sh
export JSON_STRING='window.configs = { \
  "VUE_APP_ROOT_API":"'${VUE_APP_ROOT_API}'", \
  "VUE_APP_KEYCLOAK_ISSUER":"'${VUE_APP_KEYCLOAK_ISSUER}'", \
  "VUE_APP_KEYCLOAK_CLIENT_ID":"'${VUE_APP_KEYCLOAK_CLIENT_ID}'", \
  "VUE_APP_KEYCLOAK_REALM":"'${VUE_APP_KEYCLOAK_REALM}'", \
  "VUE_APP_SENTRY_DSN_ENDPOINT":"'${VUE_APP_SENTRY_DSN_ENDPOINT}'", \
  "VUE_APP_HELPHERO":"'${VUE_APP_HELPHERO}'", \
  "VUE_APP_STRIPE_API":"'${VUE_APP_STRIPE_API}'", \
  "VUE_APP_BOT_URL":"'${VUE_APP_BOT_URL}'", \
  "VUE_APP_2FA_APP_ANDROID":"'${VUE_APP_2FA_APP_ANDROID}'", \
  "VUE_APP_2FA_APP_IOS":"'${VUE_APP_2FA_APP_IOS}'", \
  "FLOWS_GENERIC_TOKEN":"'${FLOWS_GENERIC_TOKEN}'", \
  "MODULES_YAML":"'${MODULES_YAML}'", \
  "PROJECTS_WHERE_BRAIN_IS_SHOWN":"'${PROJECTS_WHERE_BRAIN_IS_SHOWN}'", \
}'
sed "s|\/\/CONFIGURATIONS_PLACEHOLDER|${JSON_STRING}|" /usr/share/nginx/html/connect/index.html.tmpl > /tmp/index.html

exec "$@"
