export const AccountInitOptions = [
  {
    id: 0,
    title: 'account.init.facilities.title',
    disabled: false,
    value: 'facilities',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.facilities.gestao_compras_imoveis' },
      { id: 1, title: 'account.init.facilities.gestao_compras_imoveis' },
      { id: 2, title: 'account.init.facilities.gestao_investimentos' },
      { id: 3, title: 'account.init.facilities.vendas_imoveis' },
      { id: 4, title: 'account.init.facilities.gerenciamento_fornecedores' },
      { id: 5, title: 'account.init.facilities.gerenciamento_facilities' },
      {
        id: 6,
        title: 'account.init.facilities.negociacao_contratacao_fornecedores',
      },
      {
        id: 7,
        title: 'account.init.facilities.solicitacao_facilities',
        insert: true,
      },
    ],
  },
  {
    id: 1,
    title: 'account.init.product_development.title',
    disabled: false,
    value: 'product_development',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.product_development.roadmap' },
      { id: 1, title: 'account.init.product_development.solicitacoes_dev' },
      { id: 2, title: 'account.init.product_development.acompanhamento_bug' },
      {
        id: 3,
        title: 'account.init.product_development.gestao_colaborativa_ideias',
      },
      { id: 4, title: 'account.init.product_development.design_produto' },
      { id: 5, title: 'account.init.product_development.feedback_produto' },
      { id: 6, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 2,
    title: 'account.init.shared_services.title',
    disabled: false,
    value: 'services',
    icon: 'bank',
    break: true,
    options: [
      { id: 0, title: 'account.init.shared_services.cs_support' },
      { id: 1, title: 'account.init.shared_services.finance' },
      { id: 2, title: 'account.init.shared_services.rh' },
      { id: 3, title: 'account.init.shared_services.ti' },
      { id: 4, title: 'account.init.shared_services.buy' },
      { id: 5, title: 'account.init.shared_services.shared' },
      { id: 6, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 3,
    title: 'account.init.sells.title',
    disabled: false,
    value: 'sells',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.sells.qualificacao_leads' },
      { id: 1, title: 'account.init.sells.gestao_pedidos' },
      { id: 2, title: 'account.init.sells.funil' },
      { id: 3, title: 'account.init.sells.cotacao' },
      { id: 4, title: 'account.init.sells.solicitacao' },
      { id: 5, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 4,
    title: '👩‍💼 Recursos Humanos',
    disabled: false,
    value: 'rh',
    icon: '',
    options: [
      { id: 0, title: 'Recrutamento' },
      { id: 1, title: 'Onboarding de Colaboradores' },
      { id: 2, title: 'Solicitação de RH' },
      { id: 3, title: 'Solicitação de Abertura de Vagas' },
      { id: 4, title: 'Avaliação de Desenpenho' },
      { id: 5, title: 'Admisão Digital' },
      { id: 6, title: 'Outros', insert: true },
    ],
  },
  {
    id: 5,
    title: '⌨️ Financeiro e Compras',
    disabled: false,
    value: 'finance',
    icon: '',
    options: [
      { id: 0, title: 'Processo de Compras' },
      { id: 1, title: 'Contas a Pagar' },
      { id: 2, title: 'Contas a Receber' },
      { id: 3, title: 'Segunda Via de boleto' },
      { id: 4, title: 'Status Financeiro' },
      { id: 5, title: 'Parcelas' },
      { id: 6, title: 'Extrato' },
      { id: 7, title: 'Outros', insert: true },
    ],
  },
  {
    id: 6,
    title: '📞 CS e Suporte',
    disabled: false,
    value: 'cs_suport',
    icon: '',
    options: [
      { id: 0, title: 'Gerenciamento de Churn' },
      { id: 1, title: 'Feedback do Cliente' },
      { id: 2, title: 'Customer Operations' },
      { id: 3, title: 'Customer Sucess' },
      { id: 4, title: 'Suporte ao Cliente' },
      { id: 5, title: 'Parcelas' },
      { id: 6, title: 'Solicitação de Customer Sucess' },
      { id: 7, title: 'Outros', insert: true },
    ],
  },
  {
    id: 7,
    title: '⚖️ Jurídico',
    disabled: false,
    value: 'juridic',
    icon: '',
    options: [
      { id: 0, title: 'Análise de Contratos' },
      { id: 1, title: 'Redação de Contratos' },
      { id: 2, title: 'Criação de Contratos' },
      { id: 3, title: 'Solicitações para Jurídico' },
      { id: 4, title: 'Outros', insert: true },
    ],
  },
  {
    id: 8,
    title: '✈️ Supply Chain',
    disabled: false,
    value: 'supply_chain',
    icon: '',
    options: [
      { id: 0, title: 'Distribuição / Transporte' },
      { id: 1, title: 'Expedição' },
      { id: 2, title: 'Gestão de Frota' },
      { id: 3, title: 'Gestão de Frete' },
      { id: 4, title: 'Importação e Exportação' },
      { id: 5, title: 'Planejamento de compras de Materias' },
      { id: 6, title: 'Atendimento de Pedidos' },
      { id: 7, title: 'Solicitação Supply Chain' },
      { id: 8, title: 'Outros', insert: true },
    ],
  },
  {
    id: 9,
    title: '🚀 Operações de Negócios',
    disabled: false,
    value: 'operations',
    icon: '',
    options: [
      { id: 0, title: 'Gestão Colaborativa de Ideias' },
      { id: 1, title: 'Hancking de Crescimento' },
      { id: 2, title: 'Gestão de Tarefa de Equipe' },
      { id: 3, title: 'Solicitações e operações de negócios' },
      { id: 4, title: 'Outros', insert: true },
    ],
  },
  {
    id: 10,
    title: '📜 Marketing',
    disabled: false,
    value: 'marketing',
    icon: '',
    options: [
      { id: 0, title: 'Gestão de Campanha' },
      { id: 1, title: 'Gestão Colaborativa de Ideias' },
      { id: 2, title: 'Marketing de Conteúdo' },
      { id: 3, title: 'Planejamento de Evento' },
      { id: 4, title: 'Hacking de Crescimento' },
      { id: 5, title: 'Solicitação de Marketing' },
      { id: 6, title: 'Pesquisas' },
      { id: 7, title: 'Gestão de SEM' },
      { id: 8, title: 'Outros', insert: true },
    ],
  },
  {
    id: 11,
    title: '💻 TI',
    disabled: false,
    value: 'ti',
    icon: '',
    options: [
      { id: 0, title: 'Solicitação de Acesso' },
      { id: 1, title: 'Gerenciamentos de Ativos de T.I' },
      { id: 2, title: 'Suporte de T.I' },
      { id: 3, title: 'Onboarding de T.I' },
      { id: 4, title: 'Gerenciamentos de Problemas de T.I' },
      { id: 5, title: 'Solicitação para T.I' },
      { id: 6, title: 'Gerenciamentos de Incidentes de T.I' },
      { id: 7, title: 'Outros', insert: true },
    ],
  },
  {
    id: 12,
    title: 'Outros',
    disabled: false,
    value: 'others',
    insert: true,
    icon: '',
    options: [],
  },
];
