export const AccountInitOptions = [
  {
    id: 0,
    title: 'account.init.facilities.title',
    disabled: false,
    value: 'facilities',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.facilities.gestao_compras_imoveis' },
      { id: 1, title: 'account.init.facilities.gestao_compras_imoveis' },
      { id: 2, title: 'account.init.facilities.gestao_investimentos' },
      { id: 3, title: 'account.init.facilities.vendas_imoveis' },
      { id: 4, title: 'account.init.facilities.gerenciamento_fornecedores' },
      { id: 5, title: 'account.init.facilities.gerenciamento_facilities' },
      {
        id: 6,
        title: 'account.init.facilities.negociacao_contratacao_fornecedores',
      },
      {
        id: 7,
        title: 'account.init.facilities.solicitacao_facilities',
        insert: true,
      },
    ],
  },
  {
    id: 1,
    title: 'account.init.product_development.title',
    disabled: false,
    value: 'product_development',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.product_development.roadmap' },
      { id: 1, title: 'account.init.product_development.solicitacoes_dev' },
      { id: 2, title: 'account.init.product_development.acompanhamento_bug' },
      {
        id: 3,
        title: 'account.init.product_development.gestao_colaborativa_ideias',
      },
      { id: 4, title: 'account.init.product_development.design_produto' },
      { id: 5, title: 'account.init.product_development.feedback_produto' },
      { id: 6, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 2,
    title: 'account.init.shared_services.title',
    disabled: false,
    value: 'services',
    icon: 'bank',
    break: true,
    options: [
      { id: 0, title: 'account.init.shared_services.cs_support' },
      { id: 1, title: 'account.init.shared_services.finance' },
      { id: 2, title: 'account.init.shared_services.rh' },
      { id: 3, title: 'account.init.shared_services.ti' },
      { id: 4, title: 'account.init.shared_services.buy' },
      { id: 5, title: 'account.init.shared_services.shared' },
      { id: 6, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 3,
    title: 'account.init.sells.title',
    disabled: false,
    value: 'sells',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.sells.qualificacao_leads' },
      { id: 1, title: 'account.init.sells.gestao_pedidos' },
      { id: 2, title: 'account.init.sells.funil' },
      { id: 3, title: 'account.init.sells.cotacao' },
      { id: 4, title: 'account.init.sells.solicitacao' },
      { id: 5, insert: true, title: 'account.init.others' },
    ],
  },
  {
    id: 4,
    title: 'account.init.rh.title',
    disabled: false,
    value: 'rh',
    icon: '',
    options: [
      { id: 0, title: 'account.init.rh.recrutamento' },
      { id: 1, title: 'account.init.rh.onboarding' },
      { id: 2, title: 'account.init.rh.solicitacao' },
      { id: 3, title: 'account.init.rh.solicitacao_abertura' },
      { id: 4, title: 'account.init.rh.avaliacao' },
      { id: 5, title: 'account.init.rh.admisao' },
      { id: 6, title: 'Outros', insert: true },
    ],
  },
  {
    id: 5,
    title: 'account.init.financeiro.title',
    disabled: false,
    value: 'finance',
    icon: '',
    options: [
      { id: 0, title: 'account.init.financeiro.processo' },
      { id: 1, title: 'account.init.financeiro.cp' },
      { id: 2, title: 'account.init.financeiro.cr' },
      { id: 3, title: 'account.init.financeiro.segunda' },
      { id: 4, title: 'account.init.financeiro.status' },
      { id: 5, title: 'account.init.financeiro.parcelas' },
      { id: 6, title: 'account.init.financeiro.extrato' },
      { id: 7, title: 'Outros', insert: true },
    ],
  },
  {
    id: 6,
    title: 'account.init.cs.title',
    disabled: false,
    value: 'cs_suport',
    icon: '',
    options: [
      { id: 0, title: 'account.init.cs.gerenciamento' },
      { id: 1, title: 'account.init.cs.feedback' },
      { id: 2, title: 'account.init.cs.co' },
      { id: 3, title: 'account.init.cs.cs' },
      { id: 4, title: 'account.init.cs.sc' },
      { id: 5, title: 'account.init.cs.parcelas' },
      { id: 6, title: 'account.init.cs.solicitacao' },
      { id: 7, title: 'Outros', insert: true },
    ],
  },
  {
    id: 7,
    title: 'account.init.juridico.title',
    disabled: false,
    value: 'juridic',
    icon: '',
    options: [
      { id: 0, title: 'account.init.juridico.analise' },
      { id: 1, title: 'account.init.juridico.redacao' },
      { id: 2, title: 'account.init.juridico.criacao' },
      { id: 3, title: 'account.init.juridico.solicitacao' },
      { id: 4, title: 'Outros', insert: true },
    ],
  },
  {
    id: 8,
    title: 'account.init.supply.title',
    disabled: false,
    value: 'supply_chain',
    icon: '',
    options: [
      { id: 0, title: 'account.init.supply.distribuicao' },
      { id: 1, title: 'account.init.supply.expedicao' },
      { id: 2, title: 'account.init.supply.gestao_frota' },
      { id: 3, title: 'account.init.supply.gestao_frete' },
      { id: 4, title: 'account.init.supply.importacao' },
      { id: 5, title: 'account.init.supply.planejamento' },
      { id: 6, title: 'account.init.supply.atendimento' },
      { id: 7, title: 'account.init.supply.solicitacao' },
      { id: 8, insert: true, title: 'Outros' },
    ],
  },
  {
    id: 9,
    title: 'account.init.negocios.title',
    disabled: false,
    value: 'operations',
    icon: '',
    options: [
      { id: 0, title: 'account.init.negocios.ideias' },
      { id: 1, title: 'account.init.negocios.crescimento' },
      { id: 2, title: 'account.init.negocios.equipe' },
      { id: 3, title: 'account.init.negocios.operacoes' },
      { id: 4, title: 'account.init.others', insert: true },
    ],
  },
  {
    id: 10,
    title: 'account.init.marketing.title',
    disabled: false,
    value: 'marketing',
    icon: '',
    options: [
      { id: 0, title: 'account.init.marketing.campanha' },
      { id: 1, title: 'account.init.marketing.ideias' },
      { id: 2, title: 'account.init.marketing.conteudo' },
      { id: 3, title: 'account.init.marketing.evento' },
      { id: 4, title: 'account.init.marketing.crescimento' },
      { id: 5, title: 'account.init.marketing.solicitacao' },
      { id: 6, title: 'account.init.marketing.pesquisas' },
      { id: 7, title: 'account.init.marketing.sem' },
      { id: 8, title: 'account.init.others', insert: true },
    ],
  },
  {
    id: 11,
    title: 'account.init.ti.title',
    disabled: false,
    value: 'ti',
    icon: '',
    options: [
      { id: 0, title: 'account.init.ti.acesso' },
      { id: 1, title: 'account.init.ti.ativos' },
      { id: 2, title: 'account.init.ti.suporte' },
      { id: 3, title: 'account.init.ti.onboarding' },
      { id: 4, title: 'account.init.ti.problemas' },
      { id: 5, title: 'account.init.ti.solicitacoes' },
      { id: 6, title: 'account.init.ti.incidentes' },
      { id: 7, title: 'account.init.others', insert: true },
    ],
  },
  {
    id: 12,
    title: 'Outros',
    disabled: false,
    value: 'others',
    insert: true,
    icon: '',
    options: [],
  },
];
