export const AccountInitOptions = [
  {
    id: 0,
    title: '🏛 Facilities & Imobiliárias',
    value: 'facilities',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.facilities.leads' },
      { id: 1, title: 'account.init.facilities.pedidos' },
      { id: 2, title: 'account.init.facilities.funil' },
      { id: 3, title: 'account.init.facilities.cotacao' },
      { id: 4, title: 'account.init.facilities.solicitacao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 1,
    title: '🗂️ Desenvolvimento de Produto',
    value: 'product_development',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.facilities.leads' },
      { id: 1, title: 'account.init.facilities.pedidos' },
      { id: 2, title: 'account.init.facilities.funil' },
      { id: 3, title: 'account.init.facilities.cotacao' },
      { id: 4, title: 'account.init.facilities.solicitacao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 2,
    title: '🤝Serviços Compartilhados',
    value: 'services',
    icon: 'bank',
    break: true,
    options: [
      { id: 0, title: 'account.init.facilities.leads' },
      { id: 1, title: 'account.init.facilities.pedidos' },
      { id: 2, title: 'account.init.facilities.funil' },
      { id: 3, title: 'account.init.facilities.cotacao' },
      { id: 4, title: 'account.init.facilities.solicitacao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 3,
    title: '📢 Vendas',
    value: 'sells',
    icon: 'bank',
    options: [
      { id: 0, title: 'account.init.facilities.leads' },
      { id: 1, title: 'account.init.facilities.pedidos' },
      { id: 2, title: 'account.init.facilities.funil' },
      { id: 3, title: 'account.init.facilities.cotacao' },
      { id: 4, title: 'account.init.facilities.solicitacao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 4,
    title: '👩‍💼 Recursos Humanos',
    value: 'rh',
    icon: '',
    options: [
      { id: 0, title: 'account.init.facilities.leads' },
      { id: 1, title: 'account.init.facilities.pedidos' },
      { id: 2, title: 'account.init.facilities.funil' },
      { id: 3, title: 'account.init.facilities.cotacao' },
      { id: 4, title: 'account.init.facilities.solicitacao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 5,
    title: '⌨️ Financeiro e Compras',
    value: 'finance',
    icon: '',
    options: [
      { id: 0, title: 'account.init.facilities.recrutamento' },
      { id: 1, title: 'account.init.facilities.onboard' },
      { id: 2, title: 'account.init.facilities.solicitacaorh' },
      { id: 3, title: 'account.init.facilities.solicitacaoav' },
      { id: 4, title: 'account.init.facilities.avd' },
      { id: 4, title: 'account.init.facilities.admissao' },
      { id: 5, title: 'account.init.others.title' },
    ],
  },
  {
    id: 6,
    title: '📞 CS e Suporte',
    value: 'cs_suport',
    icon: '',
    options: [],
  },
  { id: 7, title: '⚖️ Jurídico', value: 'juridic', icon: '', options: [] },
  {
    id: 8,
    title: '✈️ Supply Chain',
    value: 'supply_chain',
    icon: '',
    options: [],
  },
  {
    id: 9,
    title: '🚀 Operações de Negócios',
    value: 'operations',
    icon: '',
    options: [],
  },
  { id: 10, title: '📜 Marketing', value: 'marketing', icon: '', options: [] },
  { id: 11, title: '💻 TI', value: 'ti', icon: '', options: [] },
  { id: 12, title: 'Outros', value: 'others', icon: '', options: [] },
];
