<template>
  <UnnnicModal
    @close="$emit('close')"
    :text="$t('register.modals.fail.title')"
    :description="$t('register.modals.fail.description')"
    modalIcon="warning"
    scheme="aux-red-500"
  >
  </UnnnicModal>
</template>
